name: contess
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0=openblas
  - bottleneck=1.3.2=py38hf1fa96c_1
  - bzip2=1.0.8=h0d85af4_4
  - c-ares=1.17.1=h0d85af4_1
  - ca-certificates=2022.2.1=hecd8cb5_0
  - certifi=2021.10.8=py38hecd8cb5_2
  - cmake=3.19.6=h04fa861_0
  - expat=2.4.1=he49afe7_0
  - freetype=2.11.0=hd8bbffd_0
  - giflib=5.2.1=haf1e3a3_0
  - jinja2=3.0.2=pyhd3eb1b0_0
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9d=h9ed2024_0
  - krb5=1.19.1=hcfbf3a7_0
  - lcms2=2.12=hf1fd2bf_0
  - libblas=3.9.0=10_openblas
  - libcblas=3.9.0=10_openblas
  - libcurl=7.77.0=hf45b732_0
  - libcxx=12.0.0=h2f01273_0
  - libedit=3.1.20191231=h0678c8f_2
  - libev=4.33=haf1e3a3_1
  - libffi=3.3=h046ec9c_2
  - libgfortran=3.0.1=h93005f0_2
  - liblapack=3.9.0=10_openblas
  - libnghttp2=1.43.0=h07e645a_0
  - libopenblas=0.3.17=h9a5756b_1
  - libpng=1.6.37=ha441bb4_0
  - libssh2=1.9.0=h52ee1ee_6
  - libtiff=4.2.0=h87d7836_0
  - libuv=1.41.0=hbcf498f_0
  - libwebp=1.2.2=h56c3ce4_0
  - libwebp-base=1.2.2=hca72f7f_0
  - llvm-openmp=12.0.1=hda6cdc1_1
  - lz4-c=1.9.3=h046ec9c_0
  - markupsafe=2.0.1=py38h9ed2024_0
  - ncurses=6.2=h2e338ed_4
  - ninja=1.10.2=h9a9d8cb_0
  - numexpr=2.7.3=py38h7ec9b2a_1
  - numpy=1.21.2=py38h0fa1045_0
  - numpy-base=1.21.2=py38hbbe2e76_0
  - openssl=1.1.1m=hca72f7f_0
  - pandas=1.4.1=py38he9d5cce_0
  - pillow=9.0.1=py38hde71d04_0
  - pip=21.1.3=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - python=3.8.10=h0e5c897_0_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytz=2021.1=pyhd3eb1b0_0
  - readline=8.1=h05e3726_0
  - rhash=1.4.1=h35c211d_0
  - scikit-learn=1.0.2=py38hae1ba45_1
  - scipy=1.7.3=py38hfb86763_0
  - setuptools=49.6.0=py38h50d1736_3
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=h23a322b_0
  - svgpathtools=1.4.1=pyhd8ed1ab_0
  - svgwrite=1.4.1=pyhd8ed1ab_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.10=h0419947_1
  - wheel=0.36.2=pyhd3deb0d_0
  - xz=5.2.5=haf1e3a3_1
  - zlib=1.2.11=h7795811_1010
  - zstd=1.4.9=h322a384_0
  - pip:
    - astroid==2.6.2
    - isort==5.9.2
    - lazy-object-proxy==1.6.0
    - mccabe==0.6.1
    - pylint==2.9.3
    - toml==0.10.2
    - wrapt==1.12.1
